addons:
  sonarcloud:
    organization: "alecwilliams-github" # the key of the org you chose at step #3
    token:
      secure: 08a0f2d02b23792c14d2088f7acf09dc584ca68c # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
